version: '3.3'

services:
  db:
    image: mysqlcompose # crio a imagem com esse nome quando fa√ßo build
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3307:3307"
    networks:
      - dockercompose
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/init.sql
  
  flask:
    depends_on: 
      - db
    image: flaskcompose
    ports:
      - "5000:5000"
    restart: always
    networks: 
      - dockercompose

networks:
  dockercompose: